baseURL = 'https://example.org/'
locale = 'fr'
title = 'Images des religieuses'
theme = 'ananke'
enableRobotsTXT = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[privacy.googleAnalytics]
respectDoNotTrack = true
