baseURL = 'https://lydiebrunetti.github.io/imagesdesreligieuses/'
locale = 'fr'
title = 'Images des religieuses'
theme = 'ananke'
enableRobotsTXT = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[privacy.googleAnalytics]
respectDoNotTrack = true

[menu]
  [[menu.footer]]
    name = "Mentions légales"
    url = "/privacy/"
    weight = 10